version: '3'

services:

  phpfpm:
    container_name: exd-php
    image: exd-php
    build:
      context: ./docker-files/dev/php
    env_file:
      - .env.local
    user: "1000:1000"
    volumes:
      - .:/app

  nginx:
    container_name: exd-nginx
    image: exd-nginx
    build:
      context: docker-files/dev/nginx
    env_file:
      - .env.local
    ports:
      - 8081:80
    depends_on:
      - phpfpm
    volumes:
      - .:/app
